//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: AboutDlg.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef CODELITE_LITEEDITOR_ABOUTDLG_BASE_CLASSES_H
#define CODELITE_LITEEDITOR_ABOUTDLG_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/hyperlink.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class AboutDlgBase : public wxDialog
{
protected:
    wxStaticText* m_staticText5;
    wxStaticText* m_staticText13;
    wxHyperlinkCtrl* m_hyperLink9;

protected:

public:
    wxStaticText* GetStaticText5() { return m_staticText5; }
    wxStaticText* GetStaticText13() { return m_staticText13; }
    wxHyperlinkCtrl* GetHyperLink9() { return m_hyperLink9; }
    AboutDlgBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Sowicm's Codepad"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1, -1), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~AboutDlgBase();
};

#endif
